name: my first workflow

on: push

jobs:
    my1stjob:
        runs-on: ubuntu-latest
        steps:
        - name: welcome msz
          run: echo "my first gh action job"

        - name: list files
          run: ls
        - name: read file
          run: cat README.md
        - name: checkout to read repo file
          uses: actions/checkout@v4

